### ISSUE TITLE
Asynchronous/parallel running of accounts feature request

### ISSUE THREAD

**Issue by tboy1337** [masterking32/MCF_Blum#2]
One by one approach is ok with a small number of accounts but the more accounts you have the worse it is. With 50+ accounts it takes many hours to get back to the first account. I really can't stress enough how important this feature is.

I understand your reluctant to implement this feature because of rate limiting but if you are using proxies it then isn’t relevant, you should worry about rate limiting per IP not per bot instance so I propose that the bot checks if there is a working proxy set on the account and if there is to only worry about rate limiting per IP.

The reason this should be implemented is because the more accounts you have the worse the bots performance is and therefore the less money you will make due to the larger customers not using your bot.

**Comment by masterking32** [comment]
https://github.com/masterking32/MCF_Blum/commit/84425b4fe344dea8cd8feab30c2394da5874d0c8

**Comment by tboy1337** [comment]
🎉
